Add cassanda jmx to discovery
signalfx/splunk-otel-collector pull request #5112
Opened 2024-07-17 21:03 UTC by hughesjj

to test locally, first start a cassandra cluster with `docker compose --file docker/docker-compose.yml --profile cassandra up`

Then, `make bundle.d && make otelcol && make integration-test-jmx-discovery`

2024-07-22 19:49 UTC, jeffreyc-splunk requested changes

2024-07-22 19:49 UTC, jeffreyc-splunk commented on .github/workflows/integration-test.yml
> +              elif [ "$service" != "jmx/cassandra" && "arm64" != "$arch" ]; then
Need double brackets:
```suggestion
              elif [[ "$service" != "jmx/cassandra" && "arm64" != "$arch" ]]; then
```

2024-07-24 21:41 UTC, samiura commented
@hughesjj LGTM but may be we should wait for jeff's comment.

2024-07-24 21:41 UTC, samiura approved these changes

2024-07-24 21:41 UTC, samiura commented
needs to rebase as well

2024-07-29 15:42 UTC, jeffreyc-splunk approved these changes

2024-07-29 15:49 UTC, merged