Add an example showing how to compare traces over time with Splunk Enterprise
signalfx/splunk-otel-collector pull request #899
Opened 2021-10-28 23:48 UTC by atoulme

2021-10-29 18:04 UTC, tmorrisonsfx requested changes
Changes requested.

2021-10-29 22:48 UTC, atoulme commented on examples/splunk-hec-traces/README.md
> +Splunk is configured to receive data from the OpenTelemetry Collector using the HTTP Event collector. To learn more about HEC, visit [our guide](https://dev.splunk.com/enterprise/docs/dataapps/httpev
Will use Splunk Enterprise throughout. Fixed sentence. Using Splunk OpenTelemetry Connector throughout.

2021-10-29 22:48 UTC, atoulme commented on examples/splunk-hec-traces/README.md
> +You can also search traces for information, such as querying by tag or any element of traces, by searching the traces index `index=traces`
Added period to the sentence.

2021-10-29 22:49 UTC, atoulme commented
Thanks for the review @tmorrisonsfx ! Please review my changes at leisure.

2021-11-02 12:23 UTC, tmorrisonsfx commented on examples/splunk-hec-traces/README.md
> +2. Open a terminal
Can you add punctuation to steps 1 and 2?

2021-11-02 12:23 UTC, tmorrisonsfx commented on examples/splunk-hec-traces/README.md
> +You can stop the example by pressing Ctrl+C.
Suggested change: `Ctrl + C`

2021-11-02 12:24 UTC, tmorrisonsfx approved these changes
A few minor suggestions. Thanks!

2021-11-03 16:44 UTC, atoulme commented
Thanks, changes applied, ready for merge.

2021-11-03 19:57 UTC, tmorrisonsfx approved these changes

2021-11-11 04:25 UTC, dmitryax approved these changes

2021-11-11 04:26 UTC, merged